### ISSUE TITLE
[multiworld] Feature TODO

### ISSUE THREAD

**Issue by olee** [ForgeEssentials/ForgeEssentialsMain#1163]
- [ ] Customize day/night cycle (either improve `/time` or add some new `/mw` command)
- [ ] Customize horizon, void-particles and other stuff (most likely can only be done via client mod)
- [ ] Allow custom world-gen
  - [ ] Space / emtpy (not even bedrock)
  - [ ] One-Biome-only
  - ...

**Comment by luacs1998** [comment]
Is it even possible to customize the day/night cycles and other world stuff? And should we do that? That seems like Mystcraft territory already...

**Comment by olee** [comment]
(^ sorry - missclick)
Mystcraft is about 'crafting' other dimensions - we want admins to be able to create specific additional worlds with custom parameters easily. Adjustable day/night cycle is one of those.

**Comment by Jumbacca** [comment]
How about offering an optional argument for world creation that will allow you to enter a generator seed for the created world.
/mw create <name> [provider] [type] [seed]

**Comment by olee** [comment]
See the command help - this was already added from the beginning:
`Usage: /mw create (name) [provider] [worldType] [seed]`

**Comment by Jumbacca** [comment]
Doh!.  It wasn't documented in the Wiki, so I missed it. =P

**Comment by DPxKnightxZero** [comment]
Wait so does this already exist? I have players wanting an all taint and some wanting an all magical forest.

**Comment by luacs1998** [comment]
No, this is a ticket asking for those stuff.

**Comment by DPxKnightxZero** [comment]
Oh alrighty let me know when you have implemented a proto-type. Also off question ... do you guys ever sleep?

**Comment by DashFury** [comment]
Could you add a [preset] argument when using the FLAT world type? it would prevent having to edit or replace the level.dat and delete the few region files generated when creating a custom superflat word.

Also, could you make mwtp teleport to exact Y coordinates? Maybe with an optional boolean argument? That's probably not a feature most people would ever need, but it has its uses.
