### ISSUE TITLE
Classloader/coremod waltzing TODO

### ISSUE THREAD

**Issue by luacs1998** [ForgeEssentials/ForgeEssentialsMain#1470]
- [x] Shade and package-rename Mixin and ASM - seems to be the only fix for #1449... (though mumfrey may do it)

- [x] Investigate whether we can load modules and libraries in the FMLConstructionEvent.

- [x] Add FMLAT manifest entry to replace current AccessTransformer special snowflake.

- [x] Consider using mixin as a maven dep instead of a git submodule.

Open as a reminder to do this over the weekend or something.

**Comment by melekaiah** [comment]
is this the whole thing that was tried to fix with update to forge?. Cuase 1400 version of forge is crashing again with latest forge essentials? 

what is the deal with the mixin? im not a great programmer, im just curious as to why it was needed, what it does etc. 

Forge essentials is literally the most essential mod on my servers. 

Id love to go back to the build of beta 6 before the mixin change happened. that was the most stable id had.

**Comment by liach** [comment]
Because cpw reverted luacs1998's commit in build 1400. Wait for it. By the way, Sponge has already released, I could not wait to make a 1.8 branch for that. The commit was kept in 1.8.
Mixin is a library for doing some asm injections without forge, used in SpongeCommon and SpongeVanilla. I think its a part of the integration of Sponge...

**Comment by luacs1998** [comment]
Keep that discussion in #1449

**Comment by luacs1998** [comment]
@olee let me know the results of your fix/derpy_mixins testing. I need to merge the branch ASAP.

**Comment by olee** [comment]
Tested the build - seems to work properly.
However I did not test it with fastcraft or other known problematic mods.

**Comment by luacs1998** [comment]
Closed in e83bdc53b8eb5e0af8e1b461047d14cd5e4dc094
