### ISSUE TITLE
[meta] Issues with Jenkins and the new website

### ISSUE THREAD

**Issue by luacs1998** [ForgeEssentials/ForgeEssentialsMain#1635]
I wouldn't want to make this under normal circumstances, but since I'm not in much of a position to change it, I'll just make an issue.

- [x] 1.8 experimental builds on the downloads page are broken (should be forgeessentials-1.8-server-dev.jar instead of forgeessentials-1.8-server.jar). This issue was raised to me on twitter, so for now I'm linking people directly to Jenkins.

- [x] We should install the [Promoted Builds Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Promoted+Builds+Plugin). This plugin allows us to promote (mark as recommended) the builds designated as milestone releases. You can run a set of tasks on promotion, like uploading to CurseForge and copying a backup. That way, a separate job for stable releases will not be needed **(which I have already deleted)**.

- [x] The latest stable builds should link to the CurseForge copy of the build instead of a copy on the server (use a HTTP redirect). This is because CurseForge has better servers than we do and we get the CurseForge author benefits from routing downloads through their site. No need to worry about ads - CF is (relatively) ad-free.

- [x] DON'T KEEP RENAMING STUFF. People set bookmarks, even though it's a Jenkins server and we do warn people that things can change without prior notice, it's a common courtesy. **This change has been reverted by me.**

If anyone finds any issues with the new www.forgeessentials.com please post here and let us know.

**Comment by luacs1998** [comment]
For the record, publishing to the Forge Maven has been re-enabled. Sometimes the server has a bad day and simply craps out.

**Comment by OvermindDL1** [comment]
Wait what happened?  Is something wrong with my server pathing or something?

**Comment by luacs1998** [comment]
A while ago we were getting 500 Internal Server Errors (or something like that) when we tried to upload.

I'll get you the logs of the offending builds if you want.

**Comment by olee** [comment]
Everything fixed now. Closing
